name: rainbow_challenge
description: Rainbow challenge

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  connectivity_plus: ^2.0.2
  dio: ^4.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_html: ^2.1.2
  flutter_localizations:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  linter: ^1.12.0
  meta: ^1.3.0
  path_provider: ^2.0.0
  qr_code_scanner: ^0.6.1
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.12
  uuid: ^3.0.4
  flutter_secure_storage: ^5.0.2
  formz: ^0.4.1
  file_picker: ^4.3.3
  collection: ^1.15.0



dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/achievements/
    - assets/icons/

  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap-Regular.ttf
        - asset: assets/fonts/Asap-Italic.ttf
          style: italic
        - asset: assets/fonts/Asap-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Asap-SemiBoldItalic.ttf
          style: italic
          weight: 600
    - family: Alumni Sans
      fonts:
        - asset: assets/fonts/AlumniSans-Regular.ttf
        - asset: assets/fonts/AlumniSans-Italic.ttf
          style: italic
        - asset: assets/fonts/AlumniSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AlumniSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
